os: linux
# enable a window manager to execute UI integration tests
addons:
  apt:
    packages:
      - metacity
services:
  - xvfb
  - metacity

before_install:
  - export DISPLAY=:99.0
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
  - sleep 5
  - metacity --sm-disable --replace 2> metacity.err &

branches:
	only:
	- master
	- develop
	- /release/.*/

script:
  - mvn -B verify

jobs:
  include:
    - language: java
      jdk: openjdk11
      name: OpenJDK 11
    - language: java
      jdk: openjdk8
      name: OpenJDK 8

      before_deploy:
        - mvn clean install && mvn -f ./features/org.corpus_tools.hexatomic/pom.xml cff:create && mvn clean verify

      deploy:
        - provider: releases
          api_key:
            secure: $GITHUB_TOKEN
          on:
            repo: hexatomic/hexatomic
            branch: master
            tags: true
            condition: $TRAVIS_OS_NAME = linux
          skip_cleanup: true
          draft: true
          file_glob: true
          file: releng/org.corpus_tools.hexatomic.product/target/products/hexatomic-*.zip
          tag_name: $TRAVIS_TAG
    - language: java
      jdk: openjdk11
      name: SonarCloud code analysis
      git:
        depth: false
      cache:
        directories:
          - '$HOME/.m2/repository'
          - '$HOME/.sonar/cache'
      addons:
        sonarcloud:
          organization: "hexatomic"
          token:
            secure: "DSx+XeN4OpXp/aiAQvbTekn9cBrEePnitTfLK/Farxg/0rfp2Dv+REvmRAY/GFJPfJ+mcaO0QPzOTPy7FhfDIkQkmgJjTXiQLhRLQ+WLvs5q8UyMUpS1SzKDLOQsWhyp0iVW3RicU6yJ18twfraf2t/Wz7UBfuN3O1M5Wsxspvwxe2fHkqKGlR6iOWJIefVmyS6d5MomK2DrtXdZ1HR56MKKxNOOxW90QJyU+3eEKkgWYNW5GrKdCIfJGM/maTc5AYoJgurQIrmiW+A9ILN/LUiD9ubnf4IT0uFNZA837tdA7ovM20jaOuwPGRPXiCPMHYhhmJexTrsRi1SVz172+RnRxqKmvDhB4djpbQ+SUgPTOgLUYr9g+NPA85xTs57ANqAjJi4SP0oFQyWG0tlXl6wbHp+DvvdQ/YP3M5zyPEMxFucnojx7zMxDxoNmMKFpSu4io/424FEjSTE79EVe0dsN1lm9GjkexSoftce3N9HGqRKBtx98fqa1SGi5LP102JVnTw+7Hg1ayDNeOT7ZJRu5NRrZ5KPn9s8sxFtIPUxZM0OTVDu7qwdwkeKZcszC36J+OKCvK5iJ9iNNkm5xasHmeuoVNGje14kng0McAE6BO6zWIyFG5r2B8G/e6Q/VJtR6y8fHhEjFxk9B93lHgCA0A5lAF6Ws9AvZdTnmljk="

      script:
         - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=hexatomic_hexatomic

    - language: rust
      name: Documentation

      cache:
        - cargo

      rust: stable

      before_script:
        # Set an env variable for the currently tagged version
        - export SHORT_VERSION=`echo ${TRAVIS_TAG:-develop} | sed -E 's/(\.[0-9]+)$//'`
        # Retrieve and install latest mdbook version
        - export MDBOOK_VERSION='0.3.1' # Change to use newer version
        - mkdir $HOME/.mdbook
        - curl -L -o mdbook.tar.gz https://github.com/rust-lang-nursery/mdBook/releases/download/v$MDBOOK_VERSION/mdbook-v$MDBOOK_VERSION-x86_64-unknown-linux-gnu.tar.gz && tar -C $HOME/.mdbook -xzvf mdbook.tar.gz
        - rm mdbook.tar.gz
        - export PATH=$HOME/.mdbook/mdbook:$PATH

      script:
        # Test the user documentation
        - $HOME/.mdbook/mdbook test docs/user/
        # Test the dev documentation
        - $HOME/.mdbook/mdbook test docs/dev/
        # Generate the user documentation for potential deploy
        - $HOME/.mdbook/mdbook build --dest-dir book/user/${SHORT_VERSION} docs/user/
        # Generate the dev documentation for potential deploy
        - $HOME/.mdbook/mdbook build --dest-dir book/dev/${SHORT_VERSION} docs/dev/

      deploy:
        - provider: script
          script: bash $TRAVIS_BUILD_DIR/releng/sh/deploy-docs.sh
          on:
            repo: hexatomic/hexatomic
            branch: master
            tags: true
            condition: $TRAVIS_OS_NAME = linux
          skip_cleanup: true
